name: Are iPy Notebooks Cleared

on:
  # This workflow only runs on pull requests that modify iPy Notebooks.
  pull_request:
    paths:
      - "**/*.ipynb"

jobs:
  are-ipy-notebooks-cleared:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # This is needed to get the base branch for the PR.
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Are iPy Notebooks Cleared
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: ./scripts/are_ipy_notebooks_cleared.bash
