name: Mirror Private to Public

on:
  # push:
  #   branches:
  #     - main
  #     - master
  workflow_dispatch:

jobs:
  mirror-private-to-public:
    permissions:
      contents: write
    uses: kvn-dtrx/git-hub-automatisation/.github/workflows/mirror_private_to_public.yaml@main
